[[redirects]]
  from = "/api/*"
  to = "http://7b1ba5cb.r31.cpolar.top/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin3/*"
  to = "http://7b1ba5cb.r31.cpolar.top/admin3/:splat"
  status = 200
  force = true
